myhome/apps/boardmodul/urls.py
from django.urls import path

from . import views
app_name = 'boardmodul'
urlpatterns = [
    path("", views.index, name = "index"),
    path("<int:boardmodul_id>/", views.detail, name = "detail"),
    path("<int:boardmodul_id>/leave_comment/", views.leave_comment, name = "leave_comment"),

]

myhome/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("boardmodul/", include("boardmodul.urls")),
    path('admin/', admin.site.urls),
]

myhome/apps/boardmodul/models.py
from django.db import models

class boardmodul(models.Model):
    boardmodul_title = models.CharField("modulname", max_length = 200)
    boardmodul_text = models.TextField("modulinfo")
    pub_date = models.DateTimeField("publicdate")

    def __str__(self):
        return self.boardmodul_title
class comment(models.Model):
    boardmodul = models.ForeignKey(boardmodul, on_delete = models.CASCADE)
    author_name = models.CharField("authorname", max_length = 50)
    comment_text = models.CharField("commenttext", max_length = 200)

myhome/apps/boardmodul/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from .models import boardmodul, comment
from django.urls import reverse
def index(request):
    latest_boardmodul_list = boardmodul.objects.order_by('-pub_date')[:5]
    return render(request, 'boardmodul/list.html', {'latest_boardmodul_list': latest_boardmodul_list})
def detail(request, boardmodul_id):
    try:
        a = boardmodul.objects.get( id = boardmodul_id )
    except:
        raise Http404("Seite existiert nicht")
    latest_comments_list = a.comment_set.order_by('-id')[:10]
    return render(request, 'boardmodul/detail.html', {'boardmodul': a, 'latest_comments_list': latest_comments_list})
def leave_comment(request, boardmodul_id):
    try:
        a = boardmodul.objects.get( id = boardmodul_id )
    except:
        raise Http404("Seite existiert nicht")
    a.comment_set.create(author_name = request.POST['name'], comment_text = request.POST['text'])
    return HttpResponseRedirect(reverse('boardmodul:detail', args = (a.id,)) )

myhome/templates/base.html
<!DOCTYPE html>

<html lang="de">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Meine Seite{% endblock %}</title>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

myhome/templates/boardmodul/detail.html
{% extends 'base.html' %}
{% block title %}{{boardmodul.boardmodul_title}}{% endblock %}
{% block content %}
<h2>{{boardmodul.boardmodul_title}}</h2>
<p>{{boardmodul.boardmodul_text}}</p>
<em>{{boardmodul.pub_date}}</em>
<hr>
{% if latest_comments_list %}
  {% for c in latest_comments_list %}
    <p>
      <strong>{{c.author_name}}</strong>
      <p>{{c.comment_text}}</p>
    </p>
  {% endfor %}
{% else %}
Kein Kommentar gefunden!
{% endif %}

<hr>
<form class="" action="{% url 'boardmodul:leave_comment' boardmodul.id %}" method="POST">
  {% csrf_token %}
  <input type="text" required placeholder="Ihre Nahme" name="name"><br>
  <textarea name="text" required="" placeholder="Comment Text" rows="8" cols="80"></textarea><br>
  <button type="submit">Comment Senden</button>
</form>
{% endblock %}

myhome/templates/boardmodul/list.html
{% extends 'base.html' %}
{% block title %}Letze Module{% endblock %}
{% block content %}
    {% if latest_boardmodul_list %}

      {% for a in latest_boardmodul_list %}
        <a href="{% url 'boardmodul:detail' a.id %}">{{a.boardmodul_title}}</a>
      {% endfor %}
    {% else %}
      Keinen Modul gefunden
    {% endif %}

{% endblock %}